use_frameworks!

target 'OrgUIKit_Example' do
  pod 'OrgUIKit', :path => '../'

  target 'OrgUIKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
